import type { ProjectIndex } from "@/types";

import raw from "./projects.json";

/**
 * `projects.json` is generated by `scripts/fetch-projects.mjs`, which guarantees this shape.
 * JSON imports widen literals to `string`, so the narrow union types (`ProjectKind`) need
 * the assertion.
 */
export const projectIndex = raw as ProjectIndex;
