import type { ProjectIndex } from "@/types";

import raw from "./projects.json";

// Generated by scripts/fetch-projects.mjs; JSON imports widen literals, hence the assertion.
export const projectIndex = raw as ProjectIndex;
